SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM USER;
DELETE FROM CUSTOMER;
DELETE FROM PROVIDER;
DELETE FROM GAME;
DELETE FROM KARDEX;
DELETE FROM LANGUAGE;
DELETE FROM PLATFORM;
DELETE FROM TYPE_DOCUMENT;

TRUNCATE TABLE USER;
TRUNCATE TABLE CUSTOMER;
TRUNCATE TABLE PROVIDER;
TRUNCATE TABLE GAME;
TRUNCATE TABLE KARDEX;
TRUNCATE TABLE LANGUAGE;
TRUNCATE TABLE PLATFORM;
TRUNCATE TABLE TYPE_DOCUMENT;
SET FOREIGN_KEY_CHECKS = 1;
