INSERT INTO TYPE_DOCUMENT(ID, DESCRIPTION) VALUES (1, 'CC');
INSERT INTO TYPE_DOCUMENT(ID, DESCRIPTION) VALUES (2, 'NIT');


INSERT INTO USER(ID, DOCUMENT, FULL_NAME, PASSWORD, TYPE_DOCUMENT_ID)
    VALUES(1, 1017249864, 'Pepito Cardenas', '2222222', 1);
